"""empty message

Revision ID: 7737827deb45
Revises: 33b0e52024c7
Create Date: 2021-12-06 13:46:26.415392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7737827deb45'
down_revision = '33b0e52024c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('categories', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###
