"""empty message

Revision ID: 33b0e52024c7
Revises: 5733fdd141fa
Create Date: 2021-12-06 13:45:29.739373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b0e52024c7'
down_revision = '5733fdd141fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('categories', sa.String(), nullable=False))
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'categories')
    # ### end Alembic commands ###
